### ISSUE TITLE
Question about mouseview jsPsych plugin

### ISSUE THREAD

**Issue by GEJ1** [u01ai11/MouseView.js#21]
Hello,

First of all, thank you for the excellent tool. 

I was using the jsPsych implementation and I was wondering if it's possible to keep the window still after the first touch without ending the trial (I want participants only touch one time the screen instead of inspect all around). Would I need to finish an event listener?

Best,

Gustavo.

**Comment by u01ai11** [comment]
Thanks for using the tool, apologies I haven't been very active on this repo as I'm writing up my PhD. 

Not entirely sure what you are describing without seeing the task! By window, do you mean the aperture around the mouse/touchscreen? 

Using a mouse, if you wanted to keep the blur but stop the aperture updating position you would run:

`   
document.removeEventListener('mousemove', event => {
            mouseview.datalogger.x = event.clientX - mouseview.params.offset.X;
            mouseview.datalogger.y = event.clientY - mouseview.params.offset.Y;
        }, false);
`

These lines of code deal with  removing event listeners, so duplicate them in the relevant jsPsych section 

https://github.com/u01ai11/MouseView.js/blob/master/MouseView.js#L200-L215 

I'll add making this a proper exposed function (mouseview.stopUpdating() or something) to the list of things to improve

I think that's more of a jsPsych implementation issue -- rather than a MouseView.js  library issue -- so I'm closing this for now, but I'll open a ticket for improvement and tag you in it.
